Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2024-09, with the labels that each got.

#285 Owner check fix
  A3A/addons/core/functions/Base/fn_moveOutCrew.sqf
Labels: bug, misc, ready-for-testing

#291 Community 3.7.0 updates
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Templates/Templates/STALKER/STALKER_AI_ClearSky.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_AI_ClearSky_RHS.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_AI_Freedom.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_AI_Freedom_RHS.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_AI_Military.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_AI_Military_RHS.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_AI_Monolith.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_AI_Monolith_RHS.sqf
  A3A/addons/core/functions/Base/fn_destroyCity.sqf
  A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
  A3A/addons/core/functions/Base/fn_getVehiclesGroundTransport.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackForceLand.sqf
  A3A/addons/core/functions/Supports/fn_SUP_ASFRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_UAVRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_airstrikeRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_artillery.sqf
  A3A/addons/core/functions/Supports/fn_SUP_artilleryAvailable.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf
  A3A/addons/core/functions/Supports/fn_SUP_mortarAvailable.sqf
  A3A/addons/core/functions/Supports/fn_SUP_tank.sqf
  A3A/addons/core/functions/Supports/fn_SUP_tankAvailable.sqf
  A3A/addons/core/functions/Supports/fn_SUP_tankRoutine.sqf
  A3A/addons/core/functions/Supports/fn_initSupports.sqf
  A3A/addons/core/functions/Supports/fn_showInterceptedSetupCall.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/ultimate/Stringtable.xml
Labels: bug, misc, ready-for-merge

#309 Building box
  A3A/addons/core/CfgVehicles.hpp
  A3A/addons/core/Pictures/Items/A3AU_Build_Box_Large_1.jpg
  A3A/addons/core/Pictures/Items/ammobox_black_co.paa
  A3A/addons/core/Pictures/Items/ammobox_signs_ca.paa
  A3A/addons/core/functions/init/fn_initUtilityItems.sqf
  A3A/addons/maps/BuildObjectsList.hpp
Labels: misc, ready-for-merge

#310 Helmet loss chance fix
  A3A/addons/core/functions/Revive/fn_handleDamage.sqf
  A3A/addons/core/functions/Revive/fn_handleDamageAAF.sqf
Labels: bug, ready-for-merge

#314 Money Donation
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/OrgPlayers/fn_donateMoney.sqf
  A3A/addons/core/functions/OrgPlayers/fn_donateMoneyPercentage.sqf
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/scrt/UILayouts/menu.hpp
  A3A/addons/scrt/defines.hpp
Labels: ready-for-merge

#329 Green Sea improvements
  A3A/addons/maps/Antistasi_green_sea.green_sea/mapInfo.hpp
  A3A/addons/maps/Antistasi_green_sea.green_sea/mission.sqm
Labels: map, ready-for-merge

#303 Disable Arms Dealer Parameter
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/scrt/Trader/fn_trader_createTrader.sqf
  A3A/addons/scrt/Trader/fn_trader_prepareTraderQuest.sqf
  A3A/addons/scrt/Trader/fn_trader_rerollTrader.sqf
  A3A/addons/scrt/Trader/fn_trader_setTraderDiscount.sqf
Labels: misc, ready-for-merge

#323 Fix airpoints not being added
  A3A/addons/core/Templates/Templates/FactionDefaults/EnemyDefaults.sqf
  A3A/addons/core/functions/REINF/fn_addBombRun.sqf
Labels: bug, ready-for-merge

#305 Air response changes
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/AI/fn_AIreactOnKill.sqf
  A3A/addons/core/functions/Base/fn_addRecentDamage.sqf
  A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf
  A3A/addons/core/functions/Base/fn_airspaceControl.sqf
  A3A/addons/core/functions/Base/fn_distance.sqf
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/core/functions/CREATE/fn_availableBasesAir.sqf
  A3A/addons/core/functions/CREATE/fn_vehKilledOrCaptured.sqf
  A3A/addons/core/functions/Supports/fn_SUP_ASF.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CAS.sqf
  A3A/addons/core/functions/Supports/fn_SUP_SAM.sqf
  A3A/addons/core/functions/Supports/fn_SUP_SAMAvailable.sqf
  A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: misc, ready-for-merge

#324 West/East Loyalist faction fixes
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_EM.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
Labels: bug, misc, ready-for-testing

#299 Victory/Loss Conditions, Weapon Sway bug fix
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Params.hpp
  A3A/addons/core/Pictures/Markers/EconomicVictory.paa
  A3A/addons/core/Pictures/Markers/HRLoss.paa
  A3A/addons/core/Pictures/Markers/LogisticalVictory.paa
  A3A/addons/core/Pictures/Markers/NormalVictory.paa
  A3A/addons/core/Pictures/Markers/PoliticalVictory.paa
  A3A/addons/core/Pictures/Markers/TotalVictory.paa
  A3A/addons/core/Pictures/Markers/financialLoss.paa
  A3A/addons/core/Pictures/Markers/hardcoreLoss.paa
  A3A/addons/core/Pictures/Markers/popDeath.paa
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_checkLossCondition.sqf
  A3A/addons/core/functions/Base/fn_checkWinCondition.sqf
  A3A/addons/core/functions/Base/fn_resourcesFIA.sqf
  A3A/addons/core/functions/Base/fn_statistics.sqf
  A3A/addons/core/functions/REINF/fn_controlunit.sqf
  A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
  A3A/addons/core/functions/init/fn_briefing.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
  A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
  A3A/addons/maps/MissionDescription/endMission.hpp
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/scrt/UILayouts/commanderMenu.hpp
  A3A/addons/ultimate/functions/cba/fn_settings.sqf
Labels: misc, ready-for-merge

#325 Madrigal enhancement
  A3A/addons/maps/Antistasi_OPTRE_Madrigal.OPTRE_Madrigal/mapInfo.hpp
  A3A/addons/maps/Antistasi_OPTRE_Madrigal.OPTRE_Madrigal/mission.sqm
Labels: map, ready-for-testing

#290 Potentially fix #267
  A3A/addons/core/functions/Base/fn_statistics.sqf
Labels: bug, ready-for-merge, ready-for-testing

#331 CUP LDF
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/CUP/templates.hpp
Labels: faction/template, ready-for-merge

#330 More Parameters/ options (Time/Punishments/Rally points/AI Recruitment)
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/Base/fn_chooseAttack.sqf
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/scrt/Rally/fn_rally_placeRallyPoint.sqf
  A3A/addons/scrt/Rally/fn_rally_toggleRallyPoint.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-testing

#144 QRF orbital
  A3A/addons/core/functions/Supports/fn_showInterceptedSetupCall.sqf
Labels: misc, ready-for-testing
