Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2024-10, with the labels that each got.

#362 CBA launcher variable (array > hashmap) fix
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
Labels: bug, ready-for-merge

#347 Stringtable - fix text color on Chinesesimp
  A3A/addons/scrt/Stringtable.xml
Labels: translation, ready-for-merge

#363 v11.2.1
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: bug, translation

#282 Air vehicle access on milbases
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Arid.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf
  A3A/addons/garage/Public/config.inc
Labels: misc, ready-for-merge, ready-for-testing

#332 Fast travel enabled only between major locations
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#339 economic victory needed amount fix / bug fixes
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_checkWinCondition.sqf
  A3A/addons/core/functions/REINF/fn_controlunit.sqf
  A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
  A3A/addons/core/functions/init/fn_briefing.sqf
  A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
Labels: bug, misc, ready-for-merge, ready-for-testing

#338 Project Infinite Arms Dealer
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/ProjInfAD.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/ultimate/config/trader/cfgTraderAddons.hpp
  A3A/addons/ultimate/config/trader/cfgTraderWeapons.hpp
Labels: faction/template, ready-for-merge, ready-for-testing

#348 YLArms Arms Dealer
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/ylarms.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/ultimate/config/trader/cfgTraderAddons.hpp
  A3A/addons/ultimate/config/trader/cfgTraderWeapons.hpp
Labels: faction/template, ready-for-merge, ready-for-testing

#341 CUP SFP Finnish Forces Pack
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_HAFM.sqf
  A3A/addons/core/Templates/Templates/CUP/templates.hpp
  A3A/addons/core/Templates/Templates/SWE/FFP_AI_FIN_Arctic.sqf
  A3A/addons/core/Templates/Templates/SWE/FFP_AI_FIN_Temperate.sqf
  A3A/addons/core/Templates/Templates/SWE/FFP_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/SWE/templates.hpp
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/ffp.hpp
  A3A/addons/hals/Addons/store/config/hafm.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Nodes/HAFM.hpp
  A3A/addons/ultimate/config/plane/cfgPlaneLoadouts.hpp
  A3A/addons/ultimate/config/trader/cfgTraderAddons.hpp
  A3A/addons/ultimate/config/trader/cfgTraderWeapons.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_ffp.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_ffpxa185.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_hafm.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_includes.hpp
Labels: faction/template, ready-for-merge, ready-for-testing
