Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2024-12, with the labels that each got.

#394 Fix Respawning on Chernarus Redux
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/mission.sqm
Labels: bug, ready-for-merge

#395 Fix invinciblity in RIV transfer mission
  A3A/addons/core/functions/Missions/fn_RIV_ATT_Transfer.sqf
Labels: bug, ready-for-merge

#397 Expeditionary Forces Arms Dealer
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/ef.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/ultimate/config/trader/cfgTraderAddons.hpp
  A3A/addons/ultimate/config/trader/cfgTraderWeapons.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_ef.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_includes.hpp
  Tools/csvparser/[clean].ps1
  Tools/csvparser/[parse].ps1
  Tools/csvparser/[xlsx-csv].ps1
Labels: faction/template, misc, ready-for-merge

#398 EAW Updates
  A3A/addons/core/Templates/Templates/EAW/EAW_AI_JAP_Temperate.sqf
  A3A/addons/ultimate/config/plane/cfgPlaneLoadouts.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_eaw.hpp
Labels: faction/template, ready-for-merge

#405 Add initACE to CfgFunctions.hpp
  A3A/addons/core/CfgFunctions.hpp
Labels: bug, ready-for-merge

#406 Price adjustment for the UAV support
  A3A/addons/core/functions/Supports/fn_SUP_UAV.sqf
Labels: misc, ready-for-merge

#408 11.4.0 hotfixes
  A3A/addons/core/Templates/Templates/DLC_content/gear/Artofwar/Vanilla_Riv_Remnants.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/EF/WS_NATO&UNA.sqf
  A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Arid.sqf
  A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT&SFIA.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO&UNA.sqf
Labels: bug

#409 V11.4.1
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/Templates/Templates/DLC_content/gear/Artofwar/Vanilla_Riv_Remnants.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/EF/WS_NATO&UNA.sqf
  A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Arid.sqf
  A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Remnants.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT&SFIA.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO&UNA.sqf
Labels: bug

#421 v11.4.2
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/functions/Supports/fn_SUP_UAV.sqf
  A3A/addons/core/functions/Supports/fn_initSupports.sqf
Labels: bug
