Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2024-11, with the labels that each got.

#371 Fix DC17M for Republic SF
  A3A/addons/core/Templates/Templates/CW/CW_AI_REP.sqf
  A3A/addons/core/Templates/Templates/CW/CW_AI_REP_WBK.sqf
  A3A/addons/core/Templates/Templates/CW/WM_AI_EMP.sqf
  A3A/addons/core/Templates/Templates/CW/WM_AI_EMP_Arctic.sqf
  A3A/addons/ultimate/config/trader/vehicles/vehicles_cw.hpp
Labels: bug, faction/template, ready-for-merge

#351 Vehicle Market - Use diminishing returns approach on vehicle price
  A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
  A3A/addons/ultimate/functions/REINF/fn_blackMarketVehiclePrice.sqf
Labels: misc, ready-for-merge

#368 Chernarus Redux
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/Pictures/Mission/PIC.jpg
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/Pictures/Mission/logo.paa
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/cba_settings.sqf
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/description.ext
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/initServer.sqf
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/mapInfo.hpp
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/mission.sqm
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/navGrid.sqf
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: enhancement, map, ready-for-merge

#377 Add support/transition to diwako anomalies rework
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/ultimate/CfgFunctions.hpp
  A3A/addons/ultimate/functions/STALKER/fn_cleanupAnomalyField.sqf
  A3A/addons/ultimate/functions/STALKER/fn_createAnomalyField.sqf
  A3A/addons/ultimate/functions/STALKER/fn_fillMapAnomalies.sqf
  A3A/addons/ultimate/functions/cba/fn_settings.sqf
Labels: misc, ready-for-merge

#379 Fix helmet default unlocks (again)
  A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
Labels: bug, ready-for-merge

#381 Missing semicolons fixed
  A3A/addons/logistics/Cargo/Vanilla.hpp
  A3A/addons/logistics/Nodes/RACS.hpp
  A3A/addons/ultimate/config/cfgForbiddenItemsCW.hpp
  A3A/addons/ultimate/config/cfgForbiddenItemsOPTRE.hpp
  A3A/addons/ultimate/config/trader/cfgTraderAddons.hpp
Labels: misc, ready-for-merge

#311 debatable community ports
  A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
  A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
  A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf
Labels: misc, ready-for-testing

#388 Compile gunships variable
  A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
Labels: misc, ready-for-merge
