Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2024-03, with the labels that each got.

#136 IFA C47 German Version
  A3A/addons/config_fixes/IFA/CfgVehicles.hpp
  A3A/addons/config_fixes/IFA/config.cpp
  A3A/addons/config_fixes/IFA/data/dc3_body_01_bob_co.paa
  A3A/addons/config_fixes/IFA/data/dc3_body_02_co.paa
  A3A/addons/core/Templates/Templates/CSA38/CSA_AI_WEH_Arctic.sqf
  A3A/addons/core/Templates/Templates/CSA38/CSA_AI_WEH_Arid.sqf
  A3A/addons/core/Templates/Templates/CSA38/CSA_AI_WEH_Temperate.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH_Arctic.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH_Arid.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH_Temperate.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf
Labels: enhancement, faction/template

#139 Leftovers hotfix
  A3A/addons/core/Templates/Templates/#Examples/CivilianExample.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LL.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Exegermenos.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/ultimate/config/plane/cfgPlaneLoadouts.hpp
Labels: bug

#133 vehicle loading moveOut fix
  A3A/addons/logistics/Private/fn_toggleLock.sqf
Labels: bug, misc
