Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2024-07, with the labels that each got.

#219 Black Market Store UI Rework
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/blackMarketDialog.hpp
  A3A/addons/gui/dialogues/controls.hpp
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/functions/GUI/fn_blackMarketDialog.sqf
  A3A/addons/gui/functions/GUI/fn_blackMarketTabs.sqf
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/scrt/UI/fn_ui_populateBlackMarket.sqf
  A3A/addons/ultimate/functions/blackmarket/fn_hasRequirements.sqf
Labels: misc, ready-for-merge

#226 Add forbiddenItems sale checks
  A3A/addons/hals/Addons/store/functions/server/fn_sell.sqf
  A3A/addons/ultimate/config/cfgForbiddenItems.hpp
Labels: bug, ready-for-merge

#227 Handle nil cost in fn_vehiclePrice.sqf/fn_blackMarketVehiclePrice.sqf
  A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
  A3A/addons/ultimate/functions/REINF/fn_blackMarketVehiclePrice.sqf
Labels: bug, ready-for-merge

#220 Gulfcoast Islands Port
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/Pictures/Mission/e.paa
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/Pictures/Mission/logo.paa
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/cba_settings.sqf
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/description.ext
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/initServer.sqf
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/mapInfo.hpp
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/mission.sqm
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/navGrid.sqf
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: ready-for-merge

#229 Clone Wars Update
  A3A/addons/core/Templates/Templates/CW/CW_AI_CIS.sqf
  A3A/addons/core/Templates/Templates/CW/CW_AI_CIS_WBK.sqf
  A3A/addons/core/Templates/Templates/CW/CW_Riv_DET.sqf
  A3A/addons/hals/Addons/store/config/cw.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_cw.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_optre.hpp
Labels: faction/template, ready-for-merge

#231 Send chat message when downed
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Revive/fn_unconscious.sqf
Labels: ready-for-merge

#233 Rename saves from AntistasiPlus to AntistasiUltimate
  A3A/addons/core/functions/Save/fn_collectSaveData.sqf
  A3A/addons/core/functions/Save/fn_deleteSave.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/maps/MissionDescription/master.hpp
Labels: ready-for-merge

#234 Save/load revealed zones
  A3A/addons/core/functions/Save/fn_loadServer.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/ultimate/functions/init/fn_initZones.sqf
Labels: ready-for-merge

#235 Template cleanup, LL reb mortar fix
  A3A/addons/core/Templates/Templates/3CBF/3CBF_Reb_CCM.sqf
  A3A/addons/core/Templates/Templates/3CBF/3CBF_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/3CBF/3CBF_Reb_ION.sqf
  A3A/addons/core/Templates/Templates/3CBF/3CBF_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/3CBF/3CBF_Reb_TKM.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_Reb_LM.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/BRAF/BRAF_Reb_MNGC.sqf
  A3A/addons/core/Templates/Templates/CSA38/CSA_Reb_CZE.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf
  A3A/addons/core/Templates/Templates/CW/WM_Reb_RA.sqf
  A3A/addons/core/Templates/Templates/CW/WM_Reb_RCU.sqf
  A3A/addons/core/Templates/Templates/CWR/CWR_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/EAW/EAW_Reb_CHI.sqf
  A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
  A3A/addons/core/Templates/Templates/IFA/IFA_Reb_POL.sqf
  A3A/addons/core/Templates/Templates/NFtS/NFtS_Reb_FIN_Arctic.sqf
  A3A/addons/core/Templates/Templates/NFtS/NFtS_Reb_FIN_Temperate.sqf
  A3A/addons/core/Templates/Templates/NFtS/NFtS_Reb_NOR_Arctic.sqf
  A3A/addons/core/Templates/Templates/NFtS/NFtS_Reb_NOR_Temperate.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_Reb_Ins.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Reb_NAPA.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_Reb_Ecologists.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_Reb_Ecologists_RHS.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_Reb_Loners.sqf
  A3A/addons/core/Templates/Templates/STALKER/STALKER_Reb_Loners_RHS.sqf
  A3A/addons/core/Templates/Templates/Scion/Scion_Reb_Replikas.sqf
  A3A/addons/core/Templates/Templates/UNS/UNS_Reb_VC.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_VC.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_VM.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LL.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Reb_Tura.sqf
Labels: bug, faction/template, ready-for-merge

#238 Update Stringtable.xml
  A3A/addons/scrt/Stringtable.xml
Labels: bug, ready-for-merge

#239 no vaping in WW2
  A3A/addons/core/functions/AI/fn_paradrop.sqf
Labels: bug, ready-for-merge

#240 Western Sahara update 1.1.3
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LL.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Exegermenos.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_LE.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Remnants.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Riv_ION.sqf
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/ws.hpp
Labels: faction/template, ready-for-merge

#243 One Day Staszow Will Be Finished
  A3A/addons/maps/Antistasi_Staszow.Staszow/mission.sqm
  A3A/addons/maps/Antistasi_StaszowWinter.StaszowWinter/mission.sqm
Labels: map, ready-for-merge

#245 Fix black market dropdown UI
  A3A/addons/core/Stringtable.xml
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/blackMarketDialog.hpp
  A3A/addons/gui/functions/GUI/fn_blackMarketDialog.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: bug, ready-for-merge

#201 Spectrum device functionality
  A3A/addons/core/Params.hpp
  A3A/addons/core/Scripts/SpectumDevice/sa_ewar.sqf
  A3A/addons/core/Scripts/SpectumDevice/spectrum_device.sqf
  A3A/addons/core/Scripts/SpectumDevice/stringtable.xml
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AUKUS_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AUKUS_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AUKUS_Tropical.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_Riv_CHDKZ.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_Riv_Ion.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/scrt/Encounter/fn_encounter_fleeingCivConvoy.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: ready-for-merge, ready-for-testing

#232 Arms Dealer Unlock Notifications
  A3A/addons/core/functions/Save/fn_loadServer.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
  A3A/addons/ultimate/config/trader/vehicles/vehicles_conditions.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_cw.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_optre.hpp
  Tools/csvparser/category.py
Labels: misc, ready-for-merge, ready-for-testing

#246 Display self-revive cooldown in unconscious state
  A3A/addons/core/functions/Revive/fn_unconscious.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: ready-for-merge, ready-for-testing

#249 Unable to view zone info fix
  A3A/addons/ultimate/functions/init/fn_initZones.sqf
Labels: bug, ready-for-testing

#236 Invader return framework
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/ultimate/CfgFunctions.hpp
  A3A/addons/ultimate/functions/REINF/fn_invaderComeback.sqf
  A3A/addons/ultimate/functions/REINF/fn_setInvaderState.sqf
  A3A/addons/ultimate/functions/REINF/fn_simpleAttack.sqf
Labels: enhancement, ready-for-merge

#253 CUP Militia/Loyalist Factions
  A3A/addons/config_fixes/CUP/CfgVehicles.hpp
  A3A/addons/config_fixes/CUP/config.cpp
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Pictures/Markers/marker_old_nato_co.paa
  A3A/addons/core/Pictures/Markers/marker_old_soviet_co.paa
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_EM.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_WM.sqf
  A3A/addons/core/Templates/Templates/CUP/images/flag_old_nato_co.paa
  A3A/addons/core/Templates/Templates/CUP/images/flag_old_soviet_co.paa
  A3A/addons/core/Templates/Templates/CUP/templates.hpp
Labels: faction/template, ready-for-merge

#255 Zombie themed missions
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Missions/fn_AS_Smasher.sqf
  A3A/addons/core/functions/Missions/fn_AS_Zombies.sqf
  A3A/addons/core/functions/Missions/fn_CON_Outpost_Zombies.sqf
  A3A/addons/core/functions/Missions/fn_missionRequest.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: faction/template, misc, ready-for-merge

#261 Ability to donate less than 250 (with less than 250)
  A3A/addons/core/functions/OrgPlayers/fn_donateMoney.sqf
Labels: misc, ready-for-merge

#262 Add default sell price for rival vehicles
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
Labels: misc, ready-for-merge

#202 GUNSHIP/UAV/CRUISEMISSILE supports
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Templates/Templates/CW/CW_AI_CIS.sqf
  A3A/addons/core/Templates/Templates/CW/CW_AI_CIS_WBK.sqf
  A3A/addons/core/Templates/Templates/CW/CW_AI_REP.sqf
  A3A/addons/core/Templates/Templates/CW/CW_AI_REP_WBK.sqf
  A3A/addons/core/Templates/Templates/CW/EMP_AI_EMP.sqf
  A3A/addons/core/Templates/Templates/CW/EMP_AI_EMP_WBK.sqf
  A3A/addons/core/Templates/Templates/CW/WM_AI_EMP.sqf
  A3A/addons/core/Templates/Templates/CW/WM_AI_EMP_Arctic.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_Covenant.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_Covenant_Grunts.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_UNSC.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_UNSC_desert.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_UNSC_snow.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_UNSC_tropical.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USMC_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_USMC_Temperate.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_US_Army_Arid.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_US_Army_Temperate.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/core/functions/Garrison/fn_checkVehicleType.sqf
  A3A/addons/core/functions/Garrison/fn_selectVehicleType.sqf
  A3A/addons/core/functions/REINF/fn_addBombRun.sqf
  A3A/addons/core/functions/Supports/fn_SUP_UAVRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_cruiseMissile.sqf
  A3A/addons/core/functions/Supports/fn_SUP_cruiseMissileAvailable.sqf
  A3A/addons/core/functions/Supports/fn_SUP_cruiseMissileRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunship.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunshipAvailable.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunshipRoutineDefault.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunshipRoutineNickelSteel.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunshipRoutinePelican.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunshipRoutineStarWarsHMP.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunshipRoutineStarWarsLAAT.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunshipRoutineUSAF.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunshipRoutineV44.sqf
  A3A/addons/core/functions/Supports/fn_SUP_gunshipSpawn.sqf
  A3A/addons/core/functions/Supports/fn_initSupports.sqf
  A3A/addons/core/functions/Supports/fn_showInterceptedSupportCall.sqf
  A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
Labels: faction/template, misc, ready-for-merge

#252 updated GM cargo nodes
  A3A/addons/logistics/Cargo/Vanilla.hpp
  A3A/addons/logistics/Nodes/GM.hpp
Labels: misc, ready-for-merge

#256 No insignia configs + SOG & SPE nodes and stores updated + GM store update
  A3A/addons/config_fixes/CSLA/CfgVehicles.hpp
  A3A/addons/config_fixes/CSLA/config.cpp
  A3A/addons/config_fixes/GM/CfgVehicles.hpp
  A3A/addons/config_fixes/GM/config.cpp
  A3A/addons/config_fixes/SOG/CfgVehicles.hpp
  A3A/addons/config_fixes/SOG/config.cpp
  A3A/addons/config_fixes/SPE/CfgVehicles.hpp
  A3A/addons/config_fixes/SPE/config.cpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LL.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Exegermenos.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_LE.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Remnants.sqf
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/gm.hpp
  A3A/addons/hals/Addons/store/config/spearhead.hpp
  A3A/addons/hals/Addons/store/config/vn.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/logistics/Cargo/SPE.hpp
  A3A/addons/logistics/Cargo/VN.hpp
  A3A/addons/logistics/Nodes/SPE.hpp
  A3A/addons/logistics/Nodes/VN.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_csla.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_gm.hpp
Labels: ready-for-merge

#260 New OPTRE factions
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_Insurrection.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_Reb_DME.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_Reb_ODST.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_Reb_UNSC.sqf
  A3A/addons/core/Templates/Templates/OPTRE/templates.hpp
Labels: faction/template, ready-for-merge

#264 Updated black market conditions
  A3A/addons/ultimate/config/trader/vehicles/vehicles_conditions.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_csla.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_cw.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_gm.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_includes.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_sog.hpp
  Tools/csvparser/category.py
  Tools/csvparser/common.py
  Tools/csvparser/conditions.py
Labels: misc

#265 Update infestation and conquest zombie mission
  A3A/addons/core/functions/Missions/fn_AS_Smasher.sqf
  A3A/addons/core/functions/Missions/fn_AS_Zombies.sqf
  A3A/addons/core/functions/Missions/fn_CON_Outpost_Zombies.sqf
  A3A/addons/ultimate/CfgFunctions.hpp
  A3A/addons/ultimate/functions/zombie/fn_attackHeli.sqf
  A3A/addons/ultimate/functions/zombie/fn_spawnZombie.sqf
  A3A/addons/ultimate/functions/zombie/fn_spawnZombieCrater.sqf
  A3A/addons/ultimate/functions/zombie/fn_spawnZombieRoar.sqf
  A3A/addons/ultimate/functions/zombie/fn_spawnZombieWave.sqf
  A3A/addons/ultimate/functions/zombie/fn_spawnZombieWaves.sqf
Labels: misc, ready-for-merge, ready-for-testing
