Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2024-04, with the labels that each got.

#143 Korean translation updated
  A3A/addons/core/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
  A3A/addons/scrt/Stringtable.xml
Labels: enhancement, translation

#135 moveOutCrew function and button
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Base/fn_moveOutCrew.sqf
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/scrt/UILayouts/menu.hpp
Labels: enhancement, misc

#148 Reaction Forces Arms Dealer
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/rf.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/ultimate/config/trader/cfgTraderMods.hpp
Labels: misc

#130 add csvparser + rename towngenerator
  .gitignore
  Tools/TownGenerator/input.bat
  Tools/TownGenerator/input.py
  Tools/TownGenerator/sort.py
  Tools/csvparser/README.md
  Tools/csvparser/[parse].bat
  Tools/csvparser/csv/placeholder
  Tools/csvparser/csv_operations.py
  Tools/csvparser/file_operations.py
  Tools/csvparser/output/placeholder
  Tools/csvparser/parse_operations.py
  Tools/csvparser/parser.py
  Tools/csvparser/xlsx2csv/README.md
  Tools/csvparser/xlsx2csv/[convert_xlsx_csv].bat
  Tools/csvparser/xlsx2csv/xlsx2csv.py
  Tools/sqfvalidator/sqf/analyzer.py
  Tools/validate_antistasi.ps1
Labels: documentation, enhancement

#141 hide enemy zones param
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/AI/fn_interrogate.sqf
  A3A/addons/core/functions/Base/fn_mrkWIN.sqf
  A3A/addons/core/functions/Intel/fn_selectIntel.sqf
  A3A/addons/core/functions/init/fn_initBases.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/scrt/Support/fn_support_planeReconRun.sqf
  A3A/addons/ultimate/CfgFunctions.hpp
  A3A/addons/ultimate/functions/cba/fn_settings.sqf
  A3A/addons/ultimate/functions/init/fn_initZones.sqf
  A3A/addons/ultimate/functions/zones/fn_revealRandomZones.sqf
  A3A/addons/ultimate/functions/zones/fn_revealZone.sqf
  A3A/addons/ultimate/functions/zones/fn_revealZones.sqf
  A3A/addons/ultimate/functions/zones/fn_revealZonesDistance.sqf
Labels: enhancement, misc

#159 Town changes
  A3A/addons/core/functions/Base/fn_chooseAttack.sqf
  A3A/addons/ultimate/functions/cba/fn_settings.sqf
Labels: enhancement, misc

#134 Attempt to make AI possession less annoying
  A3A/addons/scrt/AI/fn_ai_possessFriendlyUnit.sqf
Labels: enhancement, misc

#158 East Asia War Templates
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Pictures/Markers/marker_ija_ca.paa
  A3A/addons/core/Pictures/Markers/marker_roc_ca.paa
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/EAW/EAW_AI_JAP_Temperate.sqf
  A3A/addons/core/Templates/Templates/EAW/EAW_CIV.sqf
  A3A/addons/core/Templates/Templates/EAW/EAW_Reb_CHI.sqf
  A3A/addons/core/Templates/Templates/EAW/EAW_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/EAW/EAW_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/EAW/eaw_logo.paa
  A3A/addons/core/Templates/Templates/EAW/ija_flag.paa
  A3A/addons/core/Templates/Templates/EAW/roc_flag.paa
  A3A/addons/core/Templates/Templates/EAW/templates.hpp
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/eaw.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Nodes/EAW.hpp
  A3A/addons/logistics/Nodes/FOW.hpp
  A3A/addons/ultimate/config/plane/cfgPlaneLoadouts.hpp
  A3A/addons/ultimate/config/trader/cfgTraderMods.hpp
Labels: faction/template

#157 Faces of War & East Asia War templates
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Pictures/Markers/marker_ija_ca.paa
  A3A/addons/core/Pictures/Markers/marker_roc_ca.paa
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/EAW/EAW_AI_JAP_Temperate.sqf
  A3A/addons/core/Templates/Templates/EAW/EAW_CIV.sqf
  A3A/addons/core/Templates/Templates/EAW/EAW_Reb_CHI.sqf
  A3A/addons/core/Templates/Templates/EAW/EAW_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/EAW/EAW_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/EAW/eaw_logo.paa
  A3A/addons/core/Templates/Templates/EAW/ija_flag.paa
  A3A/addons/core/Templates/Templates/EAW/roc_flag.paa
  A3A/addons/core/Templates/Templates/EAW/templates.hpp
  A3A/addons/core/Templates/Templates/FoW/FOW_AI_USA_Temperate.sqf
  A3A/addons/core/Templates/Templates/FoW/FOW_AI_WEH_Temperate.sqf
  A3A/addons/core/Templates/Templates/FoW/FOW_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/FoW/fow_logo.paa
  A3A/addons/core/Templates/Templates/FoW/templates.hpp
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/eaw.hpp
  A3A/addons/hals/Addons/store/config/fow.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Nodes/EAW.hpp
  A3A/addons/logistics/Nodes/FOW.hpp
  A3A/addons/ultimate/config/plane/cfgPlaneLoadouts.hpp
  A3A/addons/ultimate/config/trader/cfgTraderMods.hpp
Labels: faction/template

#153 WarMantle Galactic Empire templates
  A3A/addons/core/Templates/Templates/CW/WM_AI_EMP.sqf
  A3A/addons/core/Templates/Templates/CW/WM_Reb_RA.sqf
  A3A/addons/core/Templates/Templates/CW/WM_Reb_RCU.sqf
  A3A/addons/core/Templates/Templates/CW/WM_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/CW/WM_Riv_GP.sqf
  A3A/addons/core/Templates/Templates/CW/flag_rebellion.paa
  A3A/addons/core/Templates/Templates/CW/templates.hpp
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/wmempire.hpp
  A3A/addons/ultimate/config/trader/cfgTraderMods.hpp
Labels: faction/template

#151 GM-vanilla implementation
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Exegermenos.sqf
Labels: faction/template

#140 Addon vehicles pack + some additions to the store
  A3A/addons/core/Templates/AddonVics.hpp
  A3A/addons/core/Templates/AddonVics/SOG_Civ.sqf
  A3A/addons/core/Templates/AddonVics/apex_Civ.sqf
  A3A/addons/core/Templates/AddonVics/contact_Civ.sqf
  A3A/addons/core/Templates/AddonVics/csla_Civ.sqf
  A3A/addons/core/Templates/AddonVics/cup_veh_Civ.sqf
  A3A/addons/core/Templates/AddonVics/d3s_Civ.sqf
  A3A/addons/core/Templates/AddonVics/gm_Civ.sqf
  A3A/addons/core/Templates/AddonVics/ivory_Civ.sqf
  A3A/addons/core/Templates/AddonVics/kart_Civ.sqf
  A3A/addons/core/Templates/AddonVics/lawsofwar_Civ.sqf
  A3A/addons/core/Templates/AddonVics/rds_Civ.sqf
  A3A/addons/core/Templates/AddonVics/reactionforces_Civ.sqf
  A3A/addons/core/Templates/AddonVics/tcgm_Civ.sqf
  A3A/addons/core/Templates/AddonVics/vanilla_Civ.sqf
  A3A/addons/core/Templates/AddonVics/westernsahara_Civ.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LL.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
  A3A/addons/hals/Addons/store/config/vanilla.hpp
Labels: enhancement, faction/template

#152 Light CSLA integration
  A3A/addons/config_fixes/Vanilla/air.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Exegermenos.sqf
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/csla.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/logistics/Cargo/CSLA.hpp
  A3A/addons/logistics/Cargo/GM.hpp
  A3A/addons/logistics/CfgLogistics.hpp
  A3A/addons/logistics/Nodes/CSLA.hpp
  A3A/addons/logistics/Nodes/GM.hpp
  A3A/addons/ultimate/config/trader/cfgTraderMods.hpp
Labels: faction/template

#172 Revert "AI heal downed Players when using Ace"
  A3A/addons/core/functions/AI/fn_askHelp.sqf
  A3A/addons/core/functions/AI/fn_help.sqf
  A3A/addons/core/functions/Revive/fn_handleDamage.sqf
  A3A/addons/core/functions/Revive/fn_handleDamageAAF.sqf
  A3A/addons/core/functions/init/fn_initACEUnconsciousHandler.sqf
  A3A/addons/scrt/AI/fn_ai_possessFriendlyUnit.sqf
Labels: bug

#178 revert Apex plane check
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LL.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
Labels: bug, faction/template

#174 Extend weather variables
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
Labels: misc

#175 Airdrop loot crate fix
  A3A/addons/core/functions/Missions/fn_LOG_Airdrop.sqf
Labels: bug, misc

#154 Translates - French
  A3A/addons/core/Stringtable.xml
  A3A/addons/gui/Stringtable.xml
  A3A/addons/hals/Stringtable.xml
  A3A/addons/jeroen_arsenal/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/ultimate/Stringtable.xml
Labels: translation

#167 add advanced towing toggle
  A3A/addons/core/Scripts/fn_advancedTowingInit.sqf
  A3A/addons/ultimate/functions/cba/fn_settings.sqf
Labels: enhancement

#165 total victory parameter
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/init/fn_resourcecheck.sqf
Labels: misc

#166 add confirmation message for rebel training
  A3A/addons/core/functions/REINF/fn_FIAskillAdd.sqf
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/scrt/UILayouts/commanderMenu.hpp
Labels: enhancement

#170 Fixed an incorrect variable name in Nato Arid template
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
Labels: faction/template

#171 3CB Faction Updates
  A3A/addons/core/Templates/Templates/3CBF/3CBF_AI_ARD.sqf
  A3A/addons/core/Templates/Templates/3CBF/3CBF_AI_HIDF.sqf
Labels: faction/template

#182 Missing mortars fix
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
Labels: bug, misc

#181 fix for naked running mercs
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Exegermenos.sqf
Labels: bug, misc

#179 forgot to fix moveout function
  A3A/addons/core/functions/Base/fn_moveOutCrew.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: bug

#163 Blackmarket guns/gear UI rework
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Vehicle_Attributes.sqf
  A3A/addons/gui/dialogues/setupDialog.hpp
  A3A/addons/gui/functions/SetupGUI/fn_setupContentTab.sqf
  A3A/addons/hals/Addons/store/dialog/defines.hpp
  A3A/addons/hals/Addons/store/dialog/sizes.hpp
  A3A/addons/hals/Addons/store/dialog/ui/itemStats.hpp
  A3A/addons/hals/Addons/store/dialog/ui/items.hpp
Labels: faction/template, misc

#190 fix for naked running Syndicate rebels
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
Labels: faction/template

#189 fix for naked running saboteurs and explosive experts
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Exegermenos.sqf
Labels: faction/template

#180 New Encounters
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Exegermenos.sqf
  A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_createVehicleCrew.sqf
  A3A/addons/core/functions/CREATE/fn_crewTypeForVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_spawnVehicle.sqf
  A3A/addons/core/functions/Revive/fn_handleDamage.sqf
  A3A/addons/scrt/CfgFunctions.hpp
  A3A/addons/scrt/Encounter/Constants.inc
  A3A/addons/scrt/Encounter/fn_encounter_HeliSlingloadCargo.sqf
  A3A/addons/scrt/Encounter/fn_encounter_fleeingCivConvoy.sqf
  A3A/addons/scrt/Encounter/fn_encounter_frontlineSkirmish.sqf
  A3A/addons/scrt/Encounter/fn_encounter_postAmbush.sqf
  A3A/addons/scrt/Encounter/fn_encounter_selectAndExecuteEvent.sqf
  A3A/addons/scrt/Encounter/fn_encounter_vehicleMove.sqf
  A3A/addons/scrt/Rivals/Constants.inc
  A3A/addons/scrt/Rivals/fn_rivals_activate.sqf
  A3A/addons/scrt/Rivals/fn_rivals_encounter_OccVsRivalsskirmish.sqf
  A3A/addons/scrt/Rivals/fn_rivals_encounter_heliRaid.sqf
  A3A/addons/scrt/Rivals/fn_rivals_selectAndExecuteEvent.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc

#169 Qrf behavior rework
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LL.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
  A3A/addons/core/functions/AI/fn_HeliDoors.sqf
  A3A/addons/core/functions/AI/fn_combatLanding.sqf
  A3A/addons/core/functions/AI/fn_fastrope.sqf
  A3A/addons/core/functions/AI/fn_fastropeVTOL.sqf
  A3A/addons/core/functions/AI/fn_paradrop.sqf
  A3A/addons/core/functions/Base/fn_getVehiclesGroundTransport.sqf
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/core/functions/CREATE/fn_FIAinitBASES.sqf
  A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
  A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf
  A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
  A3A/addons/core/functions/Revive/fn_handleDamage.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf
  A3A/addons/core/functions/Supports/fn_getArtilleryRanges.sqf
  A3A/addons/core/functions/UtilityItems/fn_initObject.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/hals/Addons/store/config/gm.hpp
  A3A/addons/scrt/Common/fn_common_paradropVehicle.sqf
  A3A/addons/scrt/Rivals/fn_rivals_encounter_uavFlyby.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc

#185 CSAT VTOL CAS/ASF
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASApproach.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASDiveRoutine.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRun.sqf
Labels: faction/template

#192 S.O.G. cargo nodes for civ vehicles
  A3A/addons/logistics/Nodes/VN.hpp
Labels: faction/template

#186 Re-implement undercover localization
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Undercover/fn_canGoUndercover.sqf
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
Labels: misc

#193 S.O.G. nickel steel
  A3A/addons/core/Templates/Templates/VN/VN_AI_ARVN.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASApproach.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
  A3A/addons/core/functions/Supports/fn_SUP_CASRun.sqf
Labels: faction/template
