Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2025-06, with the labels that each got.

#456 Weighted vehicle spawn pool for airbases
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/core/functions/CREATE/fn_createAIMilbase.sqf
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#542 Crashsite data location indication, object placement improvements
  A3A/addons/core/functions/Missions/fn_LOG_Crashsite.sqf
  A3A/addons/core/functions/Missions/fn_LOG_Crashsite_Satellite.sqf
  A3A/addons/scrt/Effect/fn_effect_crashingEffects.sqf
Labels: bug, misc, ready-for-merge

#543 Allow to unflip air/sea vehicles
  A3A/addons/scrt/Common/fn_common_unflipVehicle.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#544 Fix for Helislingload, chemlight for cargo
  A3A/addons/scrt/Encounter/fn_encounter_HeliSlingloadCargo.sqf
Labels: bug, misc, ready-for-merge

#556 Fix maxload in arsenal, substitute buggy `canAddItemTo*` calls
  A3A/addons/jeroen_arsenal/JNA/fn_vehicleArsenal.sqf
  A3A/addons/scrt/Arsenal/fn_arsenal_loadoutArsenal.sqf
  A3A/addons/scrt/CfgFunctions.hpp
  A3A/addons/scrt/Misc/fn_misc_canAddItemToContainer.sqf
Labels: misc, ready-for-merge

#558 Replace hard-code keys with custom keybinds for building placer
  A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf
  A3A/addons/core/functions/Builder/fn_initPlacerDB.sqf
  A3A/addons/core/functions/Builder/placerDefines.hpp
  A3A/addons/core/keybinds/CfgDefaultKeysPresets.hpp
  A3A/addons/core/keybinds/CfgUserActions.hpp
  A3A/addons/core/keybinds/UserActionGroups.hpp
  A3A/addons/core/keybinds/UserActionsConflictGroups.hpp
  A3A/addons/gui/functions/GUI/fn_setUpPlacerHints.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: enhancement, ready-for-merge

#566 Normalize item weights in A3A_rebelGear
  A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
Labels: misc, ready-for-merge

#568 More CUP and PRACS logistics nodes
  A3A/addons/logistics/Nodes/CUP.hpp
  A3A/addons/logistics/Nodes/RACS.hpp
Labels: faction/template, misc, ready-for-merge

#572 Remove missing pedagne dealer items
  A3A/addons/hals/Addons/store/config/italy.hpp
Labels: bug, ready-for-merge

#580 add missing parameter to A3A_fnc_SUP_mortarRoutine call
  A3A/addons/core/functions/Supports/fn_SUP_howitzer.sqf
Labels: bug, ready-for-merge

#581 Unlock limited weapons from civ interaction; unlock magazines with them
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Intel/fn_selectIntel.sqf
Labels: enhancement, ready-for-merge

#582 Side relations fix
  A3A/addons/core/functions/Base/fn_addAggression.sqf
  A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf
  A3A/addons/core/functions/Base/fn_statistics.sqf
  A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
  A3A/addons/core/functions/init/fn_briefing.sqf
  A3A/addons/core/functions/init/fn_initGarrisons.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/core/functions/init/fn_initVarServer.sqf
  A3A/addons/patcom/functions/Patcom/fn_patrolGetEnemies.sqf
Labels: bug, ready-for-merge

#583 JCA Latest Update
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/JCAArsenal.hpp
  A3A/addons/hals/Addons/store/config/JCAIA.hpp
  A3A/addons/hals/Addons/store/config/JCAIE.hpp
  A3A/addons/ultimate/config/trader/cfgTraderAddons.hpp
  A3A/addons/ultimate/config/trader/cfgTraderWeapons.hpp
Labels: enhancement, ready-for-merge

#592 Fix: Arms dealer purchase
  A3A/addons/core/functions/REINF/fn_addBlackMarketVeh.sqf
Labels: bug, ready-for-merge

#617 Missing string in convoy mission
  A3A/addons/config_fixes/3CBF/config.cpp
  A3A/addons/scrt/Stringtable.xml
Labels: misc, translation, ready-for-merge
