Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2025-05, with the labels that each got.

#520 Pistol start param
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/Ammunition/fn_itemArrayWeight.sqf
  A3A/addons/core/functions/init/fn_initServer.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#521 Šumava map changes
  A3A/addons/maps/Antistasi_brf_sumava.brf_sumava/mission.sqm
Labels: enhancement, map, ready-for-merge

#522 Ability to sell vehicles on airfields
  A3A/addons/core/functions/Base/fn_sellVehicle.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#524 More vehicle variety in convoy mission
  A3A/addons/core/CfgVehicles.hpp
  A3A/addons/core/Pictures/Items/PaperBox_01_small_money_CO.paa
  A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf
  A3A/addons/core/functions/Garrison/fn_checkVehicleType.sqf
  A3A/addons/core/functions/Missions/fn_convoy.sqf
  A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
  A3A/addons/logistics/Cargo/Vanilla.hpp
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#525 Add ability to (instantly) garage vehicles at trader
  A3A/addons/core/functions/REINF/fn_addBlackMarketVeh.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/controls.hpp
  A3A/addons/gui/functions/GUI/fn_blackMarketTabs.sqf
Labels: misc, ready-for-merge

#527 Functioning buildable helipads, but there is no twist(
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Builder/fn_buildingComplete.sqf
  A3A/addons/core/functions/Builder/fn_terrainCleaner.sqf
  A3A/addons/core/functions/Builder/fn_terrainSmoother.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/garage/Public/config.inc
  A3A/addons/garage/Stringtable.xml
  A3A/addons/maps/BuildObjectsList.hpp
Labels: misc, ready-for-merge

#529 Kunduz River Map Port
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/Pictures/Mission/logo.paa
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/cba_settings.sqf
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/description.ext
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/initServer.sqf
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/mapInfo.hpp
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/mission.sqm
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/navGrid.sqf
  A3A/addons/maps/Antistasi_kunduz_valley.kunduz_valley/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: enhancement, map, ready-for-merge

#532 Tonali Face and Voice Changes
  A3A/addons/core/Templates/Templates/CWR/CWR_AI_TDF_Arid.sqf
  A3A/addons/core/Templates/Templates/CWR/CWR_Riv_TReb.sqf
Labels: enhancement, faction/template, misc, ready-for-merge

#535 leftover blackmarket update from #426
  A3A/addons/ultimate/config/trader/cfgTraderAddons.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_csla.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_cw.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_eaw.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_ef.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_flexcdf.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_includes.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_nickelsteel.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_rf.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_sog.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_spex.hpp
  A3A/addons/ultimate/config/trader/vehicles/vehicles_vanilla.hpp
Labels: misc, ready-for-merge

#536 Don't delete stolen mission vehicles in mission cleanup
  A3A/addons/core/functions/Missions/fn_LOG_Crashsite.sqf
  A3A/addons/core/functions/Missions/fn_LOG_Crashsite_Satellite.sqf
Labels: bug, ready-for-merge

#538 Use vehicle size for fast travel position search
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: bug, ready-for-merge

#539 Translations - Korean improved
  A3A/addons/gui/Stringtable.xml
  A3A/addons/scrt/Stringtable.xml
Labels: translation, ready-for-merge

#540 SMGs to vanilla and aegis
  A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AFRF_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AFRF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AUKUS_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AUKUS_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_AUKUS_Tropical.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT&AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&LDF_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&LDF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT&SFIA.sqf
  A3A/addons/core/Templates/Templates/WS/WS_AI_NATO&UNA.sqf
  A3A/addons/core/Templates/Templates/WS/WS_Riv_ION.sqf
Labels: faction/template, ready-for-merge

#554 Add cargo loading node in trunk of Armed 4x4 SUV
  A3A/addons/logistics/Nodes/3CBFactions.hpp
Labels: faction/template, ready-for-merge

#571 Prevent garrison units from mounting ACE loaded static emplacements #2
  A3A/addons/patcom/functions/Patcom/fn_patrolArmStatics.sqf
Labels: bug, ready-for-merge

#565 Allow rivals when invaders are disabled, misc SetupGUI updates
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/setupDialog.hpp
  A3A/addons/gui/functions/SetupGUI/fn_setupDialog.sqf
  A3A/addons/gui/functions/SetupGUI/fn_setupLoadgameTab.sqf
  A3A/addons/gui/functions/SetupGUI/fn_setupParamsTab.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#552 Fix: distanceMission * 2
  A3A/addons/core/functions/Missions/fn_findIfNearAndHostile.sqf
Labels: bug, ready-for-merge

#545 Stringtable.xml tidyup
  A3A/addons/scrt/Stringtable.xml
Labels: translation, ready-for-merge

#578 CW blackmarket fix
  A3A/addons/ultimate/config/trader/vehicles/vehicles_cw.hpp
Labels: bug

#315 Additional garage categories AU
  A3A/addons/garage/CfgDefines.inc
  A3A/addons/garage/Core/fn_confirm.sqf
  A3A/addons/garage/Core/fn_confirmPlacement.sqf
  A3A/addons/garage/Core/fn_getCatIndex.sqf
  A3A/addons/garage/Core/fn_onLoad.sqf
  A3A/addons/garage/Core/fn_switchCategory.sqf
  A3A/addons/garage/Dialogs.hpp
  A3A/addons/garage/Extras/fn_findMount.sqf
  A3A/addons/garage/Extras/fn_isAmmoSource.sqf
  A3A/addons/garage/Extras/fn_isFuelSource.sqf
  A3A/addons/garage/Extras/fn_isRepairSource.sqf
  A3A/addons/garage/Extras/fn_reloadExtras.sqf
  A3A/addons/garage/Extras/fn_reloadMounts.sqf
  A3A/addons/garage/Public/config.inc
  A3A/addons/garage/Public/fn_addVehicle.sqf
  A3A/addons/garage/Public/fn_loadSaveData.sqf
  A3A/addons/garage/Refuel/fn_getTotalFuelCargo.sqf
  A3A/addons/garage/Refuel/fn_reciveStateUpdate.sqf
  A3A/addons/garage/Refuel/fn_refuelVehicleFromSources.sqf
  A3A/addons/garage/Stringtable.xml
Labels: misc, ready-for-merge
