Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2025-03, with the labels that each got.

#514 OPTRE: Remove EscapePod from vehiclesDropPod
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_UNSC.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_UNSC_desert.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_UNSC_snow.sqf
  A3A/addons/core/Templates/Templates/OPTRE/OPTRE_AI_UNSC_tropical.sqf
Labels: bug, faction/template, ready-for-merge

#510 Small BM vehicle sell fix
  A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
Labels: bug, ready-for-merge

#495 Prevent vehicles duplicating in BM UI
  A3A/addons/gui/functions/GUI/fn_blackMarketDialog.sqf
  A3A/addons/gui/functions/GUI/fn_blackMarketTabs.sqf
Labels: bug, ready-for-merge

#494 Lootcrate ignore unlocked items improvements
  A3A/addons/scrt/Loot/fn_loot_gatherLoot.sqf
  A3A/addons/ultimate/functions/Ammunition/fn_removeUnlockedItems.sqf
Labels: bug, ready-for-merge

#418 Silencers + bipods + handguns for AI rebels
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Templates/Templates/DLC_content/gear/SPE/Vanilla_FIA.sqf
  A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
  A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
  A3A/addons/core/functions/Ammunition/fn_fetchRebelGear.sqf
  A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
  A3A/addons/core/functions/Ammunition/fn_randomHandgun.sqf
  A3A/addons/core/functions/Ammunition/fn_randomRifle.sqf
  A3A/addons/core/functions/Base/fn_initPetros.sqf
  A3A/addons/core/functions/REINF/fn_equipRebel.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
Labels: misc, ready-for-merge

#446 Ambient sounds animations and civ dialogs
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Base/fn_initPetros.sqf
  A3A/addons/core/functions/Intel/fn_selectIntel.sqf
  A3A/addons/core/functions/Missions/fn_RES_Deserters.sqf
  A3A/addons/core/functions/Missions/fn_RES_Informer.sqf
  A3A/addons/core/functions/Missions/fn_RES_Prisoners.sqf
  A3A/addons/core/functions/Missions/fn_RES_Refugees.sqf
  A3A/addons/core/functions/Missions/fn_findIfNearAndHostile.sqf
  A3A/addons/core/functions/Missions/fn_missionRequest.sqf
  A3A/addons/hals/Addons/money/config.hpp
  A3A/addons/patcom/CfgFunctions.hpp
  A3A/addons/patcom/CfgSounds.hpp
  A3A/addons/patcom/functions/Civilian/fn_createAmbientCiv.sqf
  A3A/addons/patcom/functions/Civilian/fn_createAmbientCivTraffic.sqf
  A3A/addons/patcom/functions/Civilian/fn_createCivilianTracks.sqf
  A3A/addons/patcom/functions/Civilian/fn_createMusicSource.sqf
  A3A/addons/patcom/functions/Civilian/fn_createResourceCiv.sqf
  A3A/addons/patcom/functions/Civilian/fn_destroyObject.sqf
  A3A/addons/patcom/functions/Civilian/fn_destroyObjectAction.sqf
  A3A/addons/patcom/functions/Civilian/fn_dialogCiv.sqf
  A3A/addons/patcom/functions/Civilian/fn_dialogCivAction.sqf
  A3A/addons/patcom/functions/Civilian/fn_dialogCivFinished.sqf
  A3A/addons/patcom/functions/Civilian/fn_unitAmbient.sqf
  A3A/addons/patcom/functions/Civilian/fn_unitAmbientPlay.sqf
  A3A/addons/patcom/sounds/Civilian/Ambient/Breathing.lip
  A3A/addons/patcom/sounds/Civilian/Ambient/Breathing.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Coughing1.lip
  A3A/addons/patcom/sounds/Civilian/Ambient/Coughing1.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Coughing2.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Humming.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Scratching.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Sneeze.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Sniffling.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/ThroatClearing.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Whistle1.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Whistle2.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Yawn1.lip
  A3A/addons/patcom/sounds/Civilian/Ambient/Yawn1.ogg
  A3A/addons/patcom/sounds/Civilian/Ambient/Yawn2.lip
  A3A/addons/patcom/sounds/Civilian/Ambient/Yawn2.ogg
  A3A/addons/patcom/sounds/Civilian/radio2.ogg
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#460 Improve FT restrictions for HC groups
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
Labels: misc, ready-for-merge

#461 Add param to consider controlling a UAV as AFK or not
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/init/fn_clientIdleChecker.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#500 Fix bug with using not-unlocked mags in AI arsenal
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf
  A3A/addons/scrt/Arsenal/fn_arsenal_loadoutArsenal.sqf
Labels: bug, ready-for-merge

#501 Use faction-appropriate currency symbol
  A3A/addons/gui/functions/GUI/fn_blackMarketTabs.sqf
  A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
  A3A/addons/gui/functions/GUI/fn_constructTab.sqf
  A3A/addons/gui/functions/GUI/fn_donateTab.sqf
  A3A/addons/gui/functions/GUI/fn_hqDialog.sqf
  A3A/addons/gui/functions/GUI/fn_recruitDialog.sqf
  A3A/addons/gui/functions/GUI/fn_recruitSquadDialog.sqf
  A3A/addons/gui/functions/GUI/fn_setUpPlacerHints.sqf
  A3A/addons/gui/functions/GUI/fn_teamLeaderRTSPlacerDialog.sqf
Labels: misc, ready-for-merge

#506 Drone side alignment convenience fixes
  A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
  A3A/addons/garage/Public/config.inc
  A3A/addons/scrt/UILayouts/menu.hpp
Labels: misc, ready-for-merge

#508 Fix #333 - Don't allow FT to trader until located
  A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
  A3A/addons/core/functions/Missions/fn_ENC_Trader.sqf
  A3A/addons/core/functions/Save/fn_deleteSave.sqf
  A3A/addons/core/functions/Save/fn_loadServer.sqf
  A3A/addons/core/functions/Save/fn_loadStat.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: bug, ready-for-merge

#496 Lock Framework Revisited
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/core/functions/CREATE/fn_createAIMilbase.sqf
  A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/ultimate/CfgFunctions.hpp
  A3A/addons/ultimate/Stringtable.xml
  A3A/addons/ultimate/functions/vehicles/fn_addLockpickAction.sqf
  A3A/addons/ultimate/functions/vehicles/fn_isLocked.sqf
  A3A/addons/ultimate/functions/vehicles/fn_lockpick.sqf
  A3A/addons/ultimate/functions/vehicles/fn_lockpickOnFail.sqf
  A3A/addons/ultimate/functions/vehicles/fn_lockpickOnProgress.sqf
  A3A/addons/ultimate/functions/vehicles/fn_lockpickOnSuccess.sqf
  A3A/addons/ultimate/functions/vehicles/fn_lockpickZones.sqf
  A3A/addons/ultimate/functions/vehicles/fn_setLock.sqf
Labels: misc, ready-for-merge

#482 Stringtable - Add SImplified Chinese
  A3A/addons/core/Scripts/SpectumDevice/stringtable.xml
  A3A/addons/core/Stringtable.xml
  A3A/addons/gui/Stringtable.xml
  A3A/addons/hals/Stringtable.xml
  A3A/addons/jeroen_arsenal/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/ultimate/Stringtable.xml
Labels: translation, ready-for-merge

#483 Complete SetupGUI Overhaul
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/init/fn_setupMonitor.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/dialogues/setupDialog.hpp
  A3A/addons/gui/functions/SetupGUI/fn_setupDialog.sqf
  A3A/addons/gui/functions/SetupGUI/fn_setupFactionsTab.sqf
  A3A/addons/gui/functions/SetupGUI/fn_setupLoadgameTab.sqf
  A3A/addons/gui/functions/SetupGUI/fn_setupParamsTab.sqf
Labels: misc, ready-for-merge

#440 RHS GSB 2022
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Pictures/Markers/Marker_GSB2022.paa
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/RHS/RHS_AI_GSB.sqf
  A3A/addons/core/Templates/Templates/RHS/RHS_Riv_SZAVB.sqf
  A3A/addons/ultimate/config/plane/cfgPlaneLoadouts.hpp
Labels: faction/template, ready-for-merge

#469 Auto-categorize minesAPERS / minesAT and use in minefield deployment
  A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
  A3A/addons/core/functions/init/fn_initVarCommon.sqf
  A3A/addons/scrt/UI/fn_ui_setMinefieldCost.sqf
Labels: misc, ready-for-merge

#509 Improve trader mission - Only give players vague location until found
  A3A/addons/core/functions/Missions/fn_ENC_Trader.sqf
  A3A/addons/scrt/Trader/fn_trader_createTrader.sqf
Labels: misc, ready-for-merge

#526 Translations - Korean
  A3A/addons/core/Scripts/SpectumDevice/stringtable.xml
  A3A/addons/core/Stringtable.xml
  A3A/addons/gui/Stringtable.xml
  A3A/addons/hals/Stringtable.xml
  A3A/addons/jeroen_arsenal/Stringtable.xml
  A3A/addons/maps/Stringtable.xml
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/ultimate/Stringtable.xml
Labels: translation, ready-for-merge

#528 Infinity symbol in params
  A3A/addons/core/Params.hpp
Labels: misc, ready-for-merge

#507 3AS Updates Again
  A3A/addons/core/Templates/Templates/CW/CW_AI_CIS.sqf
  A3A/addons/core/Templates/Templates/CW/CW_AI_CIS_WBK.sqf
  A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
  A3A/addons/ultimate/config/trader/vehicles/vehicles_cw.hpp
Labels: faction/template, ready-for-merge

#511 Isla Duala Port
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/Pictures/Mission/logo.paa
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/cba_settings.sqf
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/description.ext
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/initServer.sqf
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/mapInfo.hpp
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/mission.sqm
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/navGrid.sqf
  A3A/addons/maps/Antistasi_isladuala3.isladuala3/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: enhancement, map, ready-for-merge

#515 Undercover from friendly airport
  A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
Labels: bug, ready-for-merge

#519 Fix autoload init hang
  A3A/addons/core/functions/Base/fn_statistics.sqf
  A3A/addons/core/functions/OrgPlayers/fn_assignBossIfNone.sqf
  A3A/addons/core/functions/init/fn_initClient.sqf
Labels: bug, ready-for-merge

#523 Money Donation Quick Fix
  A3A/addons/core/functions/OrgPlayers/fn_donateMoneyPercentage.sqf
  A3A/addons/scrt/UILayouts/menu.hpp
Labels: bug, ready-for-merge

#437 Add backend ability to disable main menu
  A3A/addons/main_menu/config.cpp
Labels: misc, ready-for-merge
