Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2025-09, with the labels that each got.

#555 Garrison group size parameter
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/CREATE/fn_createSDKgarrisons.sqf
  A3A/addons/core/functions/CREATE/fn_garrisonReorg.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#598 Add Extender Params Section
  A3A/addons/core/Params.hpp
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/functions/SetupGUI/fn_setupParamsTab.sqf
Labels: misc, ready-for-merge

#616 Kingdom of Regero Map Port
  A3A/addons/maps/Antistasi_regero.regero/Pictures/Mission/PIC.jpg
  A3A/addons/maps/Antistasi_regero.regero/Pictures/Mission/logo.paa
  A3A/addons/maps/Antistasi_regero.regero/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_regero.regero/cba_settings.sqf
  A3A/addons/maps/Antistasi_regero.regero/description.ext
  A3A/addons/maps/Antistasi_regero.regero/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_regero.regero/initServer.sqf
  A3A/addons/maps/Antistasi_regero.regero/mapInfo.hpp
  A3A/addons/maps/Antistasi_regero.regero/mission.sqm
  A3A/addons/maps/Antistasi_regero.regero/navGrid.sqf
  A3A/addons/maps/Antistasi_regero.regero/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: map, ready-for-merge

#612 Translation for #569
  A3A/addons/gui/Stringtable.xml
Labels: translation, ready-for-merge

#586 Add Lombakkan Crisis
  A3A/addons/core/CfgMarkers.hpp
  A3A/addons/core/Pictures/Markers/marker_cup_lc_boc_co.paa
  A3A/addons/core/Pictures/Markers/marker_cup_lc_luf_co.paa
  A3A/addons/core/Pictures/Markers/marker_cup_lc_nlaf_co.paa
  A3A/addons/core/Pictures/Markers/marker_cup_lc_sldf_co.paa
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_LC_NLAF.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_LC_SLDF.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Civ_AFR.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_LC_LUF.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
  A3A/addons/core/Templates/Templates/CUP/CUP_Riv_LC_BOC.sqf
  A3A/addons/core/Templates/Templates/CUP/images/CUP_LC_logo_mod.paa
  A3A/addons/core/Templates/Templates/CUP/images/flag_CUP_Civ_AFR.paa
  A3A/addons/core/Templates/Templates/CUP/templates.hpp
Labels: faction/template, ready-for-testing

#629 Added option for no death penalty (0% money loss)
  A3A/addons/core/Params.hpp
Labels: misc, ready-for-merge

#604 Movable gear/weapon store dialog
  A3A/addons/hals/Addons/store/dialog/dialog.hpp
Labels: ready-for-merge
