Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2025-02, with the labels that each got.

#399 Fapovo Map port
  A3A/addons/maps/Antistasi_fapovo.fapovo/Pictures/Mission/logo.paa
  A3A/addons/maps/Antistasi_fapovo.fapovo/Pictures/Mission/pic.jpg
  A3A/addons/maps/Antistasi_fapovo.fapovo/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_fapovo.fapovo/cba_settings.sqf
  A3A/addons/maps/Antistasi_fapovo.fapovo/description.ext
  A3A/addons/maps/Antistasi_fapovo.fapovo/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_fapovo.fapovo/initServer.sqf
  A3A/addons/maps/Antistasi_fapovo.fapovo/mapInfo.hpp
  A3A/addons/maps/Antistasi_fapovo.fapovo/mission.sqm
  A3A/addons/maps/Antistasi_fapovo.fapovo/navGrid.sqf
  A3A/addons/maps/Antistasi_fapovo.fapovo/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: map, ready-for-merge

#410 Vehicle turret magazine reload port
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/Params.hpp
  A3A/addons/core/Scripts/RRTurretMagazines/AUTHORS.txt
  A3A/addons/core/Scripts/RRTurretMagazines/LICENSE
  A3A/addons/core/Scripts/RRTurretMagazines/scripts/fn_monitorMagazines.sqf
  A3A/addons/core/Scripts/RRTurretMagazines/scripts/fn_reloadTurret.sqf
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/init/fn_initClient.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#414 Transfer mission fix
  A3A/addons/core/functions/Missions/fn_RIV_ATT_Transfer.sqf
  A3A/addons/core/functions/Missions/fn_missionRequest.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: bug, misc, ready-for-merge

#417 Missing pilot fix
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/CREATE/fn_RivalsCargoSeats.sqf
  A3A/addons/core/functions/CREATE/fn_cargoSeats.sqf
  A3A/addons/core/functions/CREATE/fn_crewTypeForVehicle.sqf
  A3A/addons/core/functions/init/fn_initRivalsVehClassToCrew.sqf
  A3A/addons/core/functions/init/fn_initVehClassToCrew.sqf
Labels: bug, ready-for-merge

#424 Fix for addon vehicle packs
  A3A/addons/core/Templates/AddonVics/SOG_Civ.sqf
  A3A/addons/core/Templates/AddonVics/apex_Civ.sqf
  A3A/addons/core/Templates/AddonVics/csla_Civ.sqf
  A3A/addons/core/Templates/AddonVics/gm_Civ.sqf
  A3A/addons/core/Templates/AddonVics/reactionforces_Civ.sqf
  A3A/addons/core/Templates/AddonVics/vanilla_Civ.sqf
  A3A/addons/core/Templates/Templates/DLC_content/vehicles/SOG/Vanilla_CIV.sqf
Labels: bug, faction/template, ready-for-merge

#442 Add missing 3CB and RHS vehicles cargo logistics nodes
  A3A/addons/logistics/Nodes/3CBFactions.hpp
  A3A/addons/logistics/Nodes/RHS.hpp
Labels: misc, ready-for-merge

#443 Misc factions updates
  A3A/addons/core/Templates/Templates/VN/VN_AI_ARVN.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT&AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&LDF_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&LDF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
Labels: bug, misc, ready-for-merge

#449 Fix player & AI arsenal tabs when using #433 and SOGPF DLC
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf
  A3A/addons/scrt/Arsenal/fn_arsenal_loadoutArsenal.sqf
Labels: misc, ready-for-merge

#451 change WM Militia to Imperial Army Troopers
  A3A/addons/core/Templates/Templates/CW/WM_AI_EMP.sqf
  A3A/addons/core/Templates/Templates/CW/WM_AI_EMP_Arctic.sqf
Labels: faction/template, ready-for-merge

#453 Player Slot Changes
  A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf
  A3A/addons/maps/Antistasi_Altis.Altis/mission.sqm
  A3A/addons/maps/Antistasi_Enoch.Enoch/mission.sqm
  A3A/addons/maps/Antistasi_Esseker.Esseker/mission.sqm
  A3A/addons/maps/Antistasi_Gulfcoast.Gulfcoast/mission.sqm
  A3A/addons/maps/Antistasi_Kapaulio.Kapaulio/mission.sqm
  A3A/addons/maps/Antistasi_Kunduz.Kunduz/mission.sqm
  A3A/addons/maps/Antistasi_Lythium.Lythium/mission.sqm
  A3A/addons/maps/Antistasi_Malden.Malden/mission.sqm
  A3A/addons/maps/Antistasi_Napf.Napf/mission.sqm
  A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mission.sqm
  A3A/addons/maps/Antistasi_OPTRE_Madrigal.OPTRE_Madrigal/mission.sqm
  A3A/addons/maps/Antistasi_Panthera3.Panthera3/mission.sqm
  A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/mission.sqm
  A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/mission.sqm
  A3A/addons/maps/Antistasi_SefrouRamal.SefrouRamal/mission.sqm
  A3A/addons/maps/Antistasi_Sehreno.Sehreno/mission.sqm
  A3A/addons/maps/Antistasi_Staszow.Staszow/mission.sqm
  A3A/addons/maps/Antistasi_StaszowWinter.StaszowWinter/mission.sqm
  A3A/addons/maps/Antistasi_Tanoa.Tanoa/mission.sqm
  A3A/addons/maps/Antistasi_Tembelan.Tembelan/mission.sqm
  A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/mission.sqm
  A3A/addons/maps/Antistasi_WW2_Omaha_Beach.WW2_Omaha_Beach/mission.sqm
  A3A/addons/maps/Antistasi_Winthera3.Winthera3/mission.sqm
  A3A/addons/maps/Antistasi_abramia.abramia/mission.sqm
  A3A/addons/maps/Antistasi_blud_vidda.blud_vidda/mission.sqm
  A3A/addons/maps/Antistasi_brf_sumava.brf_sumava/mission.sqm
  A3A/addons/maps/Antistasi_cam_lao_nam.cam_lao_nam/mission.sqm
  A3A/addons/maps/Antistasi_chernarus.chernarus/mission.sqm
  A3A/addons/maps/Antistasi_chernarus_summer.chernarus_summer/mission.sqm
  A3A/addons/maps/Antistasi_chernarus_winter.chernarus_winter/mission.sqm
  A3A/addons/maps/Antistasi_chernarusredux.chernarusredux/mission.sqm
  A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/mission.sqm
  A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mission.sqm
  A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mission.sqm
  A3A/addons/maps/Antistasi_green_sea.green_sea/mission.sqm
  A3A/addons/maps/Antistasi_iron_excelsior_Tobruk.iron_excelsior_Tobruk/mission.sqm
  A3A/addons/maps/Antistasi_lingor3.lingor3/mission.sqm
  A3A/addons/maps/Antistasi_mehland.mehland/mission.sqm
  A3A/addons/maps/Antistasi_namalsk.namalsk/mission.sqm
  A3A/addons/maps/Antistasi_pja310.pja310/mission.sqm
  A3A/addons/maps/Antistasi_psyfx_pht.psyfx_pht/mission.sqm
  A3A/addons/maps/Antistasi_pulau.pulau/mission.sqm
  A3A/addons/maps/Antistasi_rhspkl.rhspkl/mission.sqm
  A3A/addons/maps/Antistasi_ruha.ruha/mission.sqm
  A3A/addons/maps/Antistasi_sara.sara/mission.sqm
  A3A/addons/maps/Antistasi_spex_utah_beach.spex_utah_beach/mission.sqm
  A3A/addons/maps/Antistasi_stozec.stozec/mission.sqm
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/mission.sqm
  A3A/addons/maps/Antistasi_takistan.takistan/mission.sqm
  A3A/addons/maps/Antistasi_tem_anizay.tem_anizay/mission.sqm
  A3A/addons/maps/Antistasi_tem_chernarus.tem_chernarus/mission.sqm
  A3A/addons/maps/Antistasi_tem_chernarusw.tem_chernarusw/mission.sqm
  A3A/addons/maps/Antistasi_tem_kujari.tem_kujari/mission.sqm
  A3A/addons/maps/Antistasi_vn_khe_sanh.vn_khe_sanh/mission.sqm
  A3A/addons/maps/Antistasi_vt7.vt7/mission.sqm
  A3A/addons/maps/Antistasi_yulakia.yulakia/mission.sqm
  A3A/addons/scrt/Stringtable.xml
Labels: enhancement, misc, ready-for-merge

#455 Improve build box with parameters, less saving restrictions
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/Base/fn_garbageCleaner.sqf
  A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf
  A3A/addons/core/functions/Builder/fn_placeBuilderObjects.sqf
  A3A/addons/core/functions/Save/fn_saveLoop.sqf
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/ultimate/Stringtable.xml
Labels: misc, ready-for-merge

#458 Miscellaneous fixes and changes
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT&AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&LDF_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
  A3A/addons/core/functions/Ammunition/fn_fillLootCrate.sqf
  A3A/addons/core/functions/Base/fn_citySupportChange.sqf
  A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
  A3A/addons/scrt/Encounter/fn_encounter_civHeli.sqf
  A3A/addons/scrt/Encounter/fn_encounter_civPlane.sqf
  A3A/addons/scrt/Encounter/fn_encounter_fleeingCivConvoy.sqf
  A3A/addons/scrt/Rivals/fn_rivals_destroyLocation.sqf
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/scrt/UI/fn_ui_assignRivalsAttackLocationEventHandler.sqf
Labels: bug, misc, ready-for-merge

#468 Fix petros identity/name
  A3A/addons/core/functions/Base/fn_createPetros.sqf
  A3A/addons/core/functions/Base/fn_initPetros.sqf
  A3A/addons/core/functions/Utility/fn_setIdentity.sqf
  A3A/addons/core/functions/Utility/fn_setIdentityLocal.sqf
Labels: bug

#467 Improve SetupGUI Params Tab
  A3A/addons/core/Params.hpp
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/dialogues/setupDialog.hpp
  A3A/addons/gui/functions/SetupGUI/fn_setupParamsTab.sqf
Labels: misc

#484 Fix for MilAdministrations capturing themselves upon spawning
  A3A/addons/scrt/Common/fn_common_getMilAdminGarrisonPositions.sqf
Labels: bug, ready-for-merge

#472 Recruit surrendered AI to squad rework
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/AI/fn_captureX.sqf
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#475 Anomaly setting changes, fixed logging
  A3A/addons/ultimate/functions/STALKER/fn_createAnomalyField.sqf
  A3A/addons/ultimate/functions/STALKER/fn_fillMapAnomalies.sqf
  A3A/addons/ultimate/functions/cba/fn_settings.sqf
Labels: misc, ready-for-merge

#480 More reliable mag lookup in itemArrayWeight
  A3A/addons/core/functions/Ammunition/fn_itemArrayWeight.sqf
Labels: bug, ready-for-merge

#499 v11.5.3
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/AI/fn_captureX.sqf
  A3A/addons/core/functions/Ammunition/fn_itemArrayWeight.sqf
  A3A/addons/core/functions/Base/fn_flagaction.sqf
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/dialogues/ids.inc
  A3A/addons/gui/dialogues/setupDialog.hpp
  A3A/addons/gui/functions/SetupGUI/fn_setupParamsTab.sqf
  A3A/addons/scrt/Common/fn_common_getMilAdminGarrisonPositions.sqf
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/ultimate/functions/STALKER/fn_createAnomalyField.sqf
  A3A/addons/ultimate/functions/STALKER/fn_fillMapAnomalies.sqf
  A3A/addons/ultimate/functions/cba/fn_settings.sqf
Labels: bug, misc

#462 Double amount of loadouts generated per unit type
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/Templates/fn_loadFaction.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#477 Add arsenal crate action to quickly equip a loadout
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal_init.sqf
  A3A/addons/ultimate/Stringtable.xml
Labels: misc, ready-for-merge

#478 Prevent garrison units from mounting ACE loaded static emplacements
  A3A/addons/core/functions/CREATE/fn_createSDKgarrisons.sqf
Labels: bug, ready-for-merge

#481 Misc Faction UI Flag / Logo Changes / Fixes
  A3A/addons/core/Templates/Templates.hpp
  A3A/addons/core/Templates/Templates/Misc/flags/flag_zomb_dmg_co.paa
  A3A/addons/core/Templates/Templates/Misc/templates.hpp
  A3A/addons/core/Templates/Templates/VN/VN_AI_ARVN.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf
  A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_VC.sqf
  A3A/addons/core/Templates/Templates/VN/VN_Reb_VM.sqf
  A3A/addons/core/Templates/Templates/VN/flags/flag_vn_combined_co.paa
Labels: misc, ready-for-merge

#486 Prevent bad append to unlockedXYZ
  A3A/addons/core/functions/init/fn_initServer.sqf
Labels: bug, ready-for-merge

#464 Various stringtable rewordings and fixes
  A3A/addons/core/Stringtable.xml
  A3A/addons/garage/Stringtable.xml
  A3A/addons/gui/Stringtable.xml
  A3A/addons/gui/functions/GUI/fn_playerTab.sqf
  A3A/addons/hals/Stringtable.xml
  A3A/addons/scrt/Stringtable.xml
Labels: translation, ready-for-merge

#465 Black market parameters, fixes and improvements
  A3A/addons/core/Params.hpp
  A3A/addons/core/Stringtable.xml
  A3A/addons/core/functions/Intel/fn_selectIntel.sqf
  A3A/addons/core/functions/Missions/fn_LOG_Crashsite.sqf
  A3A/addons/core/functions/Missions/fn_LOG_Crashsite_Satellite.sqf
  A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
  A3A/addons/hals/Addons/store/functions/client/ui/fn_main.sqf
  A3A/addons/scrt/Stringtable.xml
  A3A/addons/ultimate/functions/REINF/fn_blackMarketVehiclePrice.sqf
Labels: bug, misc, ready-for-merge

#466 SPEX C-47 template support
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_AI_USA.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_AI_WEH.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/SPE_REB_FFF.sqf
  A3A/addons/core/Templates/Templates/SPE_IFA/templates.hpp
  A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf
Labels: faction/template, misc, ready-for-merge

#473 Missing semicolons fixed
  A3A/addons/ultimate/config/trader/cfgTraderWeapons.hpp
Labels: misc, ready-for-merge

#485 Convoy spam fix
  A3A/addons/core/functions/Base/fn_chooseAttack.sqf
  A3A/addons/core/functions/Missions/fn_convoy.sqf
Labels: bug, ready-for-merge

#504 fix release error
  A3A/addons/core/Includes/script_version.hpp
  A3A/addons/core/functions/Base/fn_flagaction.sqf
Labels: bug
