Repository Antistasi-Ultimate-Community/A3-Antistasi-Ultimate, pull requests merged in 2025-01, with the labels that each got.

#404 Stubbhult Map Port
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/Pictures/Mission/PIC.jpg
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/Pictures/Mission/logo.paa
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/Pictures/Mission/whiteboard.jpg
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/cba_settings.sqf
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/description.ext
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/initPlayerLocal.sqf
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/initServer.sqf
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/mapInfo.hpp
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/mission.sqm
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/navGrid.sqf
  A3A/addons/maps/Antistasi_stubbhult.stubbhult/onPlayerRespawn.sqf
  A3A/addons/maps/NavGrid.hpp
  A3A/addons/maps/Stringtable.xml
  A3A/addons/maps/config.cpp
  A3A/addons/maps/mapInfo.hpp
Labels: map, ready-for-merge

#412 Add missing gunship entries to vanilla templates
  A3A/addons/core/Templates/Templates/DLC_content/vehicles/Apex/Vanilla_NATO&AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/vehicles/Apex/Vanilla_NATO_Arid.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
  A3A/addons/core/Templates/Templates/vehicleVariants/Vanilla_NATO_Temparate/Vanilla_NATO_Temparate.sqf
  A3A/addons/core/Templates/Templates/vehicleVariants/Vanilla_NATO_Tropical/Vanilla_NATO_Tropical.sqf
  A3A/addons/logistics/Cargo/Vanilla.hpp
Labels: faction/template, ready-for-merge

#413 Disable "smokecoverauto" parameter
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/AI/fn_paradrop.sqf
  A3A/addons/core/functions/AI/fn_smokeCoverAuto.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#415 Make qrf's go faster
  A3A/addons/core/functions/CREATE/fn_WPCreate.sqf
Labels: misc, ready-for-merge

#422 CUP Estraria
  A3A/addons/core/Templates/Templates/CUP/CUP_AI_EST.sqf
  A3A/addons/core/Templates/Templates/CUP/templates.hpp
  A3A/addons/ultimate/config/plane/cfgPlaneLoadouts.hpp
Labels: faction/template, ready-for-merge

#425 HAFM Arms Dealer Fix
  A3A/addons/core/Templates/Templates/CUP/templates.hpp
  A3A/addons/hals/Addons/store/config.hpp
  A3A/addons/hals/Addons/store/config/hafm.hpp
  A3A/addons/hals/Stringtable.xml
  A3A/addons/ultimate/config/cfgForbiddenItems.hpp
  A3A/addons/ultimate/config/cfgForbiddenItemsHAFM.hpp
Labels: bug, ready-for-merge

#427 Improve Rebel Weapon and Other Items Selection
  A3A/addons/core/CfgFunctions.hpp
  A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
  A3A/addons/core/functions/Ammunition/fn_itemArrayWeight.sqf
  A3A/addons/core/functions/Ammunition/fn_itemConfig.sqf
  A3A/addons/core/functions/REINF/fn_equipRebel.sqf
Labels: misc, ready-for-merge

#432 JCA Arms Dealer UMP Update
  A3A/addons/hals/Addons/store/config/JCAArsenal.hpp
Labels: faction/template, misc, ready-for-merge

#435 Recruit surrendered AI to player squad
  A3A/addons/core/Params.hpp
  A3A/addons/core/functions/AI/fn_captureX.sqf
  A3A/addons/core/functions/AI/fn_surrenderAction.sqf
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#374 Add support for weighted-list faction templates.
  A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/Apex/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/Artofwar/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/CSLA/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/Contact/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/GM/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/Lawsofwar/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/RF/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/SOG/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/SPE/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/gear/WS/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/weapons/Apex/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/weapons/CSLA/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/weapons/Contact/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/weapons/GM/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/weapons/Marksman/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/weapons/RF/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/weapons/SOG/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/weapons/SPE/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/DLC_content/weapons/WS/Vanilla_AAF.sqf
  A3A/addons/core/Templates/Templates/MOD_content/CUP/Vanilla_AAF/Gear_AAF.sqf
  A3A/addons/core/Templates/Templates/MOD_content/CUP/Vanilla_AAF/Weapons_AAF.sqf
  A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
  A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
Labels: misc, ready-for-merge

#429 getArtilleryRanges missing variable fix
  A3A/addons/core/functions/Supports/fn_getArtilleryRanges.sqf
Labels: bug, ready-for-merge

#430 Fixed stringtable typo in Assassination
  A3A/addons/scrt/Stringtable.xml
Labels: misc, ready-for-merge

#433 Add Ability to Edit a Weapon's Loaded Magazine(s) in the Limited Arsenal
  A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf
  A3A/addons/scrt/Arsenal/fn_arsenal_loadoutArsenal.sqf
Labels: misc, ready-for-merge

#436 Rename .sqm "Antistasi Plus" to "Antistasi Ultimate"
  A3A/addons/maps/Antistasi_SefrouRamal.SefrouRamal/mission.sqm
  A3A/addons/maps/Antistasi_Stratis.Stratis/mission.sqm
  A3A/addons/maps/Antistasi_brf_sumava.brf_sumava/mission.sqm
Labels: misc, ready-for-merge

#439 Add more Lootcrate Distance
  A3A/addons/core/Params.hpp
Labels: misc, ready-for-merge
